// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAufoulQS7d4bsWnBgE6988rM7dWbY3UNs',
    appId: '1:770750667516:web:846e9ee71aa523d3afd579',
    messagingSenderId: '770750667516',
    projectId: 'newfirebase-c5b31',
    authDomain: 'newfirebase-c5b31.firebaseapp.com',
    storageBucket: 'newfirebase-c5b31.appspot.com',
    measurementId: 'G-RQE3B27X11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcJXZOxBaACMn_8bS3exfsC0ruTSF6IWQ',
    appId: '1:770750667516:android:438bfc1866c8aed7afd579',
    messagingSenderId: '770750667516',
    projectId: 'newfirebase-c5b31',
    storageBucket: 'newfirebase-c5b31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsS0voO-Y_wZi_Lfkr9IuoA5Q6-A9Hv88',
    appId: '1:770750667516:ios:2fc38944c1a5f644afd579',
    messagingSenderId: '770750667516',
    projectId: 'newfirebase-c5b31',
    storageBucket: 'newfirebase-c5b31.appspot.com',
    iosClientId: '770750667516-kk34f1aho233qm0517dmrskggg4vvskp.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsS0voO-Y_wZi_Lfkr9IuoA5Q6-A9Hv88',
    appId: '1:770750667516:ios:2fc38944c1a5f644afd579',
    messagingSenderId: '770750667516',
    projectId: 'newfirebase-c5b31',
    storageBucket: 'newfirebase-c5b31.appspot.com',
    iosClientId: '770750667516-kk34f1aho233qm0517dmrskggg4vvskp.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApplication',
  );
}
